# Generated by Django 4.2.23 on 2025-06-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rent', models.CharField(max_length=100)),
                ('rooms', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
